import VaultControls from '../components/security/VaultControls';
import { sampleDevices, sampleSessions, policySummary } from '../components/security/previewPreferences';
import Icon from '../components/Icon';
import { Button, Card, Badge, Heading } from '../components/ui/Primitives';
function SectionTitle({icon,title,text,children}) { return <div className="security-card-title"><span className="icon-tile"><Icon name={icon} size={29}/></span><div><h2>{title}</h2><p>{text}</p></div>{children}</div>; }
export default function Security({demo,setModal,exportVault,previewPreferences={}}) {
 const toggle=(label,initial=demo)=>{ const enabled=demo && (previewPreferences[label]?.[label] ?? previewPreferences['Notification Preferences']?.[label] ?? initial); return <button type="button" className={'security-toggle '+(enabled?'on':'')} aria-label={'Configure '+label+' · '+(demo?(enabled?'On in preview':'Off in preview'):'Setup required')} onClick={()=>setModal(label)}><span/></button>; };
 const devices = previewPreferences['Trusted devices']?.entries ?? sampleDevices;
 const sessions = previewPreferences['Active sessions']?.entries ?? sampleSessions;
 const deviceRows=(showSessions=false)=>(demo?(showSessions?sessions:devices):['This browser']).map(name=><button className="device-row" key={name} onClick={()=>setModal(showSessions?'Active sessions':'Trusted devices')}><Icon name="device" size={26}/>{demo && <span className="status-dot"/>}<span><strong>{name}</strong><small>{demo?'Sample entry':'Device registry not connected'}</small></span><small>{demo?(name==='MacBook Pro'?'Current sample':'Sample trusted'):'Unverified'}</small><Icon name="chevron" size={12}/></button>);
 return <>
 <Heading title="Security, Recovery & Settings" text="Stronger today. A more secure tomorrow." eyebrow="Advanced protection, effortless control, and peace of mind for what matters most."/>
 <div className="security-reference-grid">
 <Card className="authentication-card"><SectionTitle icon="fingerprint" title="Passkeys & Biometrics" text="Sign in securely with passkeys and biometrics."><Badge tone={demo?'success':'warning'}>{demo?'Active':'Setup'}</Badge></SectionTitle>
 {[['user','Face ID / Touch ID','Use your device biometrics to sign in.'],['key','Passkeys','Sync across your trusted devices.'],['shield','Require biometric confirmation','For sensitive actions, e.g. exports and access grants.']].map(([icon,label,text])=><div className="security-control" key={label}><Icon name={icon} size={28}/><span><strong>{label}</strong><small>{text}</small></span>{toggle(label,demo)}</div>)}
 <button className="text-button mfa-link" onClick={()=>setModal('Multi-factor authentication')}>Manage multi-factor authentication <Icon name="chevron" size={12}/></button></Card>
 <Card className="recovery-card"><SectionTitle icon="file" title="Recovery Phrase" text="Your 24-word recovery phrase protects your legacy."><Badge tone={demo?'success':'warning'}>{demo?'Secure':'Review'}</Badge></SectionTitle><div className="masked-phrase" role="img" aria-label="Recovery phrase hidden"><span aria-hidden="true">••••••••••••••••••••••••</span><Icon name="eye"/></div><p className="muted">Keep your recovery phrase offline and never share it.</p><Button variant="primary" icon="lock" onClick={()=>setModal('Recovery phrase')}>View Recovery Phrase</Button><Button icon="refresh" onClick={()=>setModal('Recovery practice')}>Recovery Practice</Button></Card>
 <Card className="posture-card"><h2><Icon name="shield" size={28}/> Your Security Posture</h2><div className="posture-score"><div className="progress-ring" style={{'--progress':demo?'360deg':'0deg'}}><span>{demo?'100%':'—'}</span></div><div><h2>{demo?'Excellent':'Review'}</h2><p>{demo?'Sample protections are configured.':'Complete your protection setup.'}</p></div></div>
 {['Passkeys & Biometrics','Recovery Phrase','Trusted Devices','Encryption Status','Access policies','No suspicious activity'].map((s,i)=><div className="posture-check" key={s}><Icon name={demo?'check':'info'} size={17}/><span>{s}</span><small>{demo?['Active','Secured',`${devices.length} trusted`,'End-to-end','Configured','All clear'][i]:'Review'}</small></div>)}<blockquote>“Privacy is not a feature.<br/>It’s a responsibility.”<small>LEQVOR</small></blockquote></Card>
 <Card className="devices-card"><SectionTitle icon="device" title="Trusted Devices" text="Manage the devices that can access your account."><button className="text-button" onClick={()=>setModal('Trusted devices')}>View All ›</button></SectionTitle>{deviceRows()}</Card>
 <Card className="sessions-card"><SectionTitle icon="clock" title="Session Activity" text="Recent account activity across your devices."><button className="text-button" onClick={()=>setModal('Active sessions')}>View All ›</button></SectionTitle>{deviceRows(true)}</Card>
 </div>
 <div className="security-reference-bottom">
 <Card><SectionTitle icon="lock" title="Encryption Status" text="Your data is encrypted before upload."/>{[['Data at rest','AES-256-GCM'],['Key derivation','Argon2id'],['Encryption keys','Client-side'],['Key lifecycle','Cleared on lock']].map(([a,b])=><div className="mini-security-row" key={a}><Icon name="check" size={14}/><span>{a}</span><small>{b}</small></div>)}</Card>
 <Card><SectionTitle icon="info" title="Notification Preferences" text="Choose what you want to be notified about."/>{['Security alerts','Access requests','Important activity','Product updates'].map((s,i)=><div className="mini-security-row" key={s}><Icon name="info" size={15}/><span>{s}</span>{toggle(s,i<3)}</div>)}</Card>
 <Card><SectionTitle icon="family" title="Access Policies" text="Control how your legacy can be accessed."/>{['Shield approvals','Cold Lock','PIN scrambling','Duress Protection'].map(s=><div className="mini-security-row" key={s}><Icon name="shield" size={15}/><span>{s}</span><button className="text-button" aria-label={'Configure '+s} onClick={()=>setModal(s)}>{demo?policySummary(s,previewPreferences):'Manage'} ›</button></div>)}</Card>
 <Card><SectionTitle icon="file" title="Legal Export" text="Export your data or request deletion."/>{['Export Your Data','Import earlier records','Account deletion'].map((s,i)=><button className="export-row" key={s} onClick={()=>i===0?exportVault():setModal(s)}><Icon name={i===0?'download':'file'} size={16}/>{s}<Icon name="chevron" size={14}/></button>)}<p className="export-note"><Icon name="info" size={14}/>Sensitive actions require reauthentication.</p></Card>
 </div><div className="form-actions"><Button icon="clock" onClick={()=>setModal('Security Timeline')}>Security Timeline</Button><Button onClick={()=>setModal('Notification Preferences')}>Notification preferences</Button></div><div className="security-live-controls"><VaultControls/></div>
 </>;
}

